server:
  port: 8080
spring:
  application:
    name: APP-POS
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:contacts
    username: sa
    password: password
    driver-class-name: org.h2.Driver