server:
  port: 8080
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update